project_name: kindacool

snapshot:
  name_template: "{{ incpatch .Version }}-next"

dist: bin

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kindacool
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
    flags:
      - -trimpath

# release single binary for darwin
universal_binaries:
  - replace: true

# overwrite resulting binary names
archives:
  - format: binary
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - maintainer: Tobias Brumhard <code@brumhard.com>
    description: kindacool k3s installer.
    homepage: https://github.com/brumhard/kindacool
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  groups:
    - title: New Features and updates
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Documentation updates
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other Work
      order: 999
  filters:
    # Commit messages matching the regexp listed here will be removed from
    # the changelog
    exclude:
      - "^refactor:"
      - "^chore"

release:
  # replace existing releases with same tag
  mode: replace
  footer: |
    **OCI Image**: `docker pull ghcr.io/brumhard/kindacool:{{ .Tag }}`

    **Full Changelog**: https://github.com/brumhard/kindacool/compare/{{ .PreviousTag }}...{{ .Tag }}

kos:
  - repository: ghcr.io/brumhard/kindacool
    tags:
      - "{{ .Tag }}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: none
